### PR TITLE
Add option to detect maxima (dark spots on bright background)

### PR DESCRIPTION
**Pull request by tpietzsch**
This adds a new detector setting `DetectionType` that is used in `DoGDetectorOp` and ComboBox to set it in `AdvancedDoGDetectorDescriptor`.

image
Screenshot 2019-08-09 at 16 02 23

### CODE REVIEW

**Comment by tinevez** [comment]
Can I merge?

**Comment by tpietzsch** [comment]
After carefully reviewing it, of course :-)

**Comment by tpietzsch** [comment]
> After carefully reviewing it, of course :-)

Ok, that was my attempt at a joke...

It should be ready to merge. 👍

**Comment by tinevez** [comment]
!??!
I thought I merged it already.
Sorry my bad.

**Pull request merged**
